# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/28 15:48:53 by jecaudal          #+#    #+#              #
#    Updated: 2020/09/08 18:06:22 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb
  namespace: default
  labels:
    app: dep-influx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: img-influxdb
        env:
          - name: INFLUXDB_ADM_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: influxdb_admin_pass
          - name: INFLUXDB_TELE_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: influxdb_tele_pass
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /root/livenessprobe.sh
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: pv-influxdb
            mountPath: /var/lib/influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
      volumes:
      - name: pv-influxdb
        persistentVolumeClaim:
          claimName: pvc-influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: svc-influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - name: port-influxdb
    port: 8086
    targetPort: 8086
    protocol: TCP
