# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    secret_model.yaml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/09/01 12:00:14 by jecaudal          #+#    #+#              #
#    Updated: 2020/09/06 12:22:19 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  name: global-secret
  namespace: default
type: Opaque
data:
  wp_user_password: $1
  maria_admin_pass: $2
  influxdb_admin_pass: $3
  influxdb_tele_pass: $4
  ftps_pass: $5
  ssh_root_password: $6
