# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    secret.yaml                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/09/01 12:00:14 by jecaudal          #+#    #+#              #
#    Updated: 2020/09/06 12:21:58 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  name: global-secret
  namespace: default
type: Opaque
data:
  wp_user_password: UUZOTDRETTdFdmI5MkFtZW4zS3N5eGhvaEJzNklaRXJJNUdjU3g0cEk=
  maria_admin_pass: c3dvSER3OVFjT2xvOUlOUk1DY0VaV25CSUY3eWRwOEwzSFJUNFE=
  influxdb_admin_pass: N2lFZFZnNzVrTWhDdTdja0Z0TmZxc0JDWFpNMzM3SUtXZUxmWDJWWXJJ
  influxdb_tele_pass: VzNHQzR6Q0lwT1dSZmJUWHVFRFFrWUhrY2xDTDNEZmljbTRtZzNKdFU=
  ftps_pass: dUp2S005ejl0b1NpQjJHeERUdWVUMXpKZTRQNDY4QkRkcld0bWdSeUJR
  ssh_root_password: Q0NvYUZ6N3hISndFNTNmdzNRNVl1c1VvQW5QRzJPR0ZrTmFpOHo1Zmtz
