apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: ip-pools
        protocol: layer2
        addresses:
          - 192.168.99.230-192.168.99.240
