# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/30 13:53:42 by Lobbyra           #+#    #+#              #
#    Updated: 2020/09/01 21:41:37 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-grafana
spec:
  selector:
    matchLabels:
      app: dep-grafana
  template:
    metadata:
      labels:
        app: dep-grafana
    spec:
      containers:
      - name: dep-grafana
        image: img-grafana
        volumeMounts:
          - name: pv-grafana
            mountPath: /root/grafana/data
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      volumes:
      - name: pv-grafana
        hostPath:
          path: /mnt/grafana
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
spec:
  selector:
    app: dep-grafana
  type: LoadBalancer
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
