# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/30 13:53:42 by Lobbyra           #+#    #+#              #
#    Updated: 2020/09/04 18:37:00 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  namespace: default
  labels:
    app: dep-grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-grafana
spec:
  selector:
    matchLabels:
      app: dep-grafana
  template:
    metadata:
      labels:
        app: dep-grafana
    spec:
      containers:
      - name: dep-grafana
        image: img-grafana
        env:
          - name: INFLUXDB_TELE_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: influxdb_tele_pass
        volumeMounts:
          - name: pv-grafana
            mountPath: /root/grafana/data
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      volumes:
      - name: pv-grafana
        persistentVolumeClaim:
            claimName: pvc-grafana
---
apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
spec:
  selector:
    app: dep-grafana
  type: LoadBalancer
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
