# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/31 16:47:01 by jecaudal          #+#    #+#              #
#    Updated: 2020/08/31 17:02:28 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mariadb
spec:
  selector:
    matchLabels:
      app: dep-mariadb
  template:
    metadata:
      labels:
        app: dep-mariadb
    spec:
      containers:
      - name: dep-mariadb
        image: img-mariadb
        imagePullPolicy: Never
        env:
          - name: WP_USER_PASS
            value: 4gf8d64f8g6
          - name: ADMIN_PASS
            value: s4d8fg6fsdfg
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mariadb
spec:
  selector:
    app: dep-mariadb
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306

