# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/26 18:19:41 by jecaudal          #+#    #+#              #
#    Updated: 2020/09/08 16:56:03 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx
spec:
  selector:
    matchLabels:
      app: dep-nginx
  template:
    metadata:
      labels:
        app: dep-nginx
    spec:
      containers:
      - name: dep-nginx
        image: img-nginx
        livenessProbe:
            exec:
              command:
              - /bin/ash
              - /tmp/ft_services_payload/livenessprobe.sh
            initialDelaySeconds: 10
            periodSeconds: 10
        env:
          - name: SSH_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: ssh_root_password
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  selector:
    app: dep-nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
