# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/31 16:43:23 by jecaudal          #+#    #+#              #
#    Updated: 2020/09/08 18:00:06 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  serviceName: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: img-wordpress
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /
            port: 5050
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
          - name: WP_USER_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: wp_user_password
        ports:
        - containerPort: 5050
