# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/09/02 14:32:08 by jecaudal          #+#    #+#              #
#    Updated: 2020/09/08 12:49:08 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-telegraf
spec:
  selector:
    matchLabels:
      app: dep-telegraf
  template:
    metadata:
      labels:
        app: dep-telegraf
    spec:
      containers:
      - name: dep-telegraf
        image: img-telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 8125
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /root/livenessprobe.sh
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: svc-telegraf
spec:
  selector:
    app: dep-telegraf
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: 8125
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-telegraf
  labels:
    app: dep-telegraf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-telegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: account-telegraf
  namespace: default
