# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jecaudal <jecaudal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/30 18:02:48 by Lobbyra           #+#    #+#              #
#    Updated: 2020/09/08 18:07:21 by jecaudal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  serviceName: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: img-ftps
        env:
          - name: FTPS_USER
            value: michel
          - name: FTPS_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: ftps_pass
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /root/livenessprobe.sh
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
          - name: pv-ftps
            mountPath: /ftp
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
      volumes:
      - name: pv-ftps
        hostPath:
          path: /mnt/ftp
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: port-ftps-20
      port: 20
      targetPort: 20
    - name: port-ftps-21
      port: 21
      targetPort: 21
    - name: port-ftps-21000
      port: 21000
      targetPort: 21000
    - name: port-ftps-21001
      port: 21001
      targetPort: 21001
    - name: port-ftps-21002
      port: 21002
      targetPort: 21002
    - name: port-ftps-21003
      port: 21003
      targetPort: 21003
    - name: port-ftps-21004
      port: 21004
      targetPort: 21004
